version: 0.2


# Build and Post-Build Configuration

  ## Configuration Details

phases:
  build:
    commands:
      - echo "Build phase"
      - mvn clean package

post_build:
  commands:
    - echo "Build completed"

artifacts:
  files:
    - target/service.jar
  discard-paths: yes
